<a href="https://colab.research.google.com/github/lakhanrajpatlolla/aiml-learning/blob/master/TalentSprint_IIIT_Colab_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Advanced Certification in AIML
## A Program by IIIT-H and TalentSprint

## Tensor basics

### Setup Steps

In [ ]:
!pip3 install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 3.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 77.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 58.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 45.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 15.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 17.5 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.5.1+cu124


#**Tensor**

###Initializing a tensor

In [ ]:
# Initializing a tensor
a = torch.Tensor([2,3])
print(a.size())
print(a)

torch.Size([2])
tensor([2., 3.])


In [ ]:
a.type()

'torch.FloatTensor'

In [ ]:
t = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(t)
print(t.size())
print(t.t())

tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Creating a scalar tensor

In [ ]:
a = torch.tensor(200)
print(a)
print(a.size())
print(a.type())

tensor(200)
torch.Size([])
torch.LongTensor


###Converting scalar to python number

In [ ]:
print(a.item())
print(type(a.item()))

200
<class 'int'>


###Creating a float tensor

In [ ]:
a = torch.tensor([2.0,3])
a.type()

'torch.FloatTensor'

###Providing the data type while creating the tensor

In [ ]:
a = torch.tensor([2,3],dtype=torch.int32)
a.type()

'torch.IntTensor'

###Just like numpy, creating a tensor by copying another tensor results, pointing to same memory location









In [ ]:
a = torch.tensor([2.0, 3])
b = a
c=a.clone()
b[0] = 11
print(a)
print(b)
print(c)

tensor([11.,  3.])
tensor([11.,  3.])
tensor([2., 3.])


###2D tensor

In [ ]:
a = torch.tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1, 2],
        [3, 4]])
torch.LongTensor


In [ ]:
a = torch.Tensor([[1,2],[3,4]])
print(a)
print(a.type())

tensor([[1., 2.],
        [3., 4.]])
torch.FloatTensor


###Creating and initializing a tensor with random values

In [ ]:
a = torch.rand(3,4)
print(a)

tensor([[0.1276, 0.4317, 0.9916, 0.1817],
        [0.6753, 0.3589, 0.6333, 0.1537],
        [0.7595, 0.4174, 0.5072, 0.2446]])


###Creating and initializing a float tensor with zeros

In [ ]:
a = torch.zeros((4,5), dtype=torch.float32)
print(a)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


###Creating an Identity tensor

In [ ]:
a = torch.eye(4,4)
print(a)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#**Tensor Operations**

###Addition of two tensor

In [ ]:
x = torch.rand(3,3)
y = torch.rand(3,3)
z = x+y
print(z)

tensor([[1.5513, 0.6299, 0.9639],
        [0.5222, 1.8294, 0.6160],
        [1.4646, 1.5585, 0.7651]])


###Addition of two tensor (alternative)

In [ ]:
z = x.add(y)
print(z)
#z=x+y

tensor([[1.5513, 0.6299, 0.9639],
        [0.5222, 1.8294, 0.6160],
        [1.4646, 1.5585, 0.7651]])


In [ ]:
c=torch.tensor(20)
print(c.size())
c=torch.tensor([20])
print(c.size())
c=torch.tensor([[20]])
print(c.size())
c=torch.tensor([[[20]]])
print(c.size())

torch.Size([])
torch.Size([1])
torch.Size([1, 1])
torch.Size([1, 1, 1])


###Inplace addition of two tensor

In [ ]:
print(x)

x.add_(y)
#x=x+y

print(x)

tensor([[0.9090, 0.4799, 0.5538],
        [0.3814, 0.9160, 0.2110],
        [0.6788, 0.7827, 0.0369]])
tensor([[1.5513, 0.6299, 0.9639],
        [0.5222, 1.8294, 0.6160],
        [1.4646, 1.5585, 0.7651]])


###Element wise multiplication

In [ ]:
print(x*y)

tensor([[0.9964, 0.0945, 0.3952],
        [0.0735, 1.6709, 0.2494],
        [1.1510, 1.2091, 0.5571]])


###Matrix multiplication

In [ ]:
z = torch.matmul(x,y[:,0])
print(z)
z.size()

tensor([1.8425, 1.0770, 1.7614])


torch.Size([3])

###Reshaping tensors

In [ ]:
x = torch.rand(5,6)
print("Size of x :\n",x.size())
print("x:\n",x)
y = x.view(30)
print("Size of y :\n",y.size())
print("y:\n",y)
z = x.view(3,10)
print("Size of z :\n",z.size())
print("z:\n",z)
z = x.view(-1,10)
print("Size of z :\n",z.size())
print("z:\n",z)

Size of x :
 torch.Size([5, 6])
x:
 tensor([[0.5752, 0.2789, 0.8191, 0.2044, 0.4438, 0.9614],
        [0.1786, 0.5481, 0.5890, 0.6792, 0.8866, 0.0753],
        [0.0729, 0.1541, 0.5422, 0.5503, 0.7769, 0.8733],
        [0.4625, 0.3558, 0.2890, 0.7960, 0.9097, 0.4747],
        [0.5152, 0.9119, 0.4208, 0.5016, 0.9535, 0.3619]])
Size of y :
 torch.Size([30])
y:
 tensor([0.5752, 0.2789, 0.8191, 0.2044, 0.4438, 0.9614, 0.1786, 0.5481, 0.5890,
        0.6792, 0.8866, 0.0753, 0.0729, 0.1541, 0.5422, 0.5503, 0.7769, 0.8733,
        0.4625, 0.3558, 0.2890, 0.7960, 0.9097, 0.4747, 0.5152, 0.9119, 0.4208,
        0.5016, 0.9535, 0.3619])
Size of z :
 torch.Size([3, 10])
z:
 tensor([[0.5752, 0.2789, 0.8191, 0.2044, 0.4438, 0.9614, 0.1786, 0.5481, 0.5890,
         0.6792],
        [0.8866, 0.0753, 0.0729, 0.1541, 0.5422, 0.5503, 0.7769, 0.8733, 0.4625,
         0.3558],
        [0.2890, 0.7960, 0.9097, 0.4747, 0.5152, 0.9119, 0.4208, 0.5016, 0.9535,
         0.3619]])
Size of z :
 torch.Size([3, 10]

###Generating Numbers in Sequence

In [ ]:
x = torch.arange(9)
print(x)
x = x.view(3,3)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


###Concatenating two tensors at a given dimension

In [ ]:
print(torch.cat((x,x),dim=0))
print(torch.cat((x,x),dim=1))

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]])


###Reducing the redundant dimension by squeeze operation

In [ ]:
x1= torch.rand(1,5)
print("size of x1 squeezing:\n",x1.size())
print(x1)
x1 = x1.squeeze()
print("size of x1 after squeezing:\n", x1.size())
print(x1)

size of x1 squeezing:
 torch.Size([1, 5])
tensor([[0.3536, 0.8186, 0.8420, 0.5294, 0.5314]])
size of x1 after squeezing:
 torch.Size([5])
tensor([0.3536, 0.8186, 0.8420, 0.5294, 0.5314])


In [ ]:
x1 = torch.rand(1,1,5)
print("size of x1 before squeezing:\n", x1.size())
print(x1)
x1 = x1.squeeze()
print("size of x1 after squeezing:\n", x1.size())
print(x1)
print(x1.numpy())

size of x1 before squeezing:
 torch.Size([1, 1, 5])
tensor([[[0.1366, 0.3979, 0.4085, 0.4541, 0.9965]]])
size of x1 after squeezing:
 torch.Size([5])
tensor([0.1366, 0.3979, 0.4085, 0.4541, 0.9965])
[0.13664645 0.39786088 0.40849692 0.4541359  0.9965352 ]


In [ ]:
x2 = torch.rand(3,1,4,1,5)
print("size of x2 before squeezing:\n", x2.size())
print(x2)
x2 = x2.squeeze()
print("size of x2 after squeezing:\n", x2.size())
print(x2)

size of x2 before squeezing:
 torch.Size([3, 1, 4, 1, 5])
tensor([[[[[0.2371, 0.4476, 0.8551, 0.2201, 0.0108]],

          [[0.9178, 0.9372, 0.4717, 0.2624, 0.5428]],

          [[0.8091, 0.3367, 0.6744, 0.2808, 0.2231]],

          [[0.8950, 0.9022, 0.0172, 0.0176, 0.3202]]]],



        [[[[0.4712, 0.3305, 0.4078, 0.9796, 0.1717]],

          [[0.6894, 0.8854, 0.8833, 0.8838, 0.9970]],

          [[0.3611, 0.9187, 0.0893, 0.2255, 0.6699]],

          [[0.6828, 0.6481, 0.4441, 0.6411, 0.0795]]]],



        [[[[0.1536, 0.5694, 0.4721, 0.0741, 0.1530]],

          [[0.3897, 0.9793, 0.9707, 0.7052, 0.8337]],

          [[0.0832, 0.5157, 0.0460, 0.3986, 0.3475]],

          [[0.9157, 0.0498, 0.8912, 0.9541, 0.0368]]]]])
size of x2 after squeezing:
 torch.Size([3, 4, 5])
tensor([[[0.2371, 0.4476, 0.8551, 0.2201, 0.0108],
         [0.9178, 0.9372, 0.4717, 0.2624, 0.5428],
         [0.8091, 0.3367, 0.6744, 0.2808, 0.2231],
         [0.8950, 0.9022, 0.0172, 0.0176, 0.3202]],

        [[0.471

###Extending the dimension by unsqueeze operation

In [ ]:
x = torch.rand(3,4,5,6)
print(x.size())
#print(x)
print(x.unsqueeze(dim=2).size())
#print(x.unsqueeze(dim=2))
print(x.unsqueeze(dim=3).size())
print(x.unsqueeze(dim=4).size())

torch.Size([3, 4, 5, 6])
torch.Size([3, 4, 1, 5, 6])
torch.Size([3, 4, 5, 1, 6])
torch.Size([3, 4, 5, 6, 1])


###Numpy Bridge
####Converting a numpy array to torch tensor

In [ ]:
x = np.array([[1.0,2],[3,4]])
print(type(x))
y = torch.from_numpy(x)
print(y)
y.type()

<class 'numpy.ndarray'>
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


'torch.DoubleTensor'

####Converting a torch tensor to numpy array

In [ ]:
z = y.numpy()
z.dtype

dtype('float64')

**CUDA Tensors**

####Checking the availability of CUDA/GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# Linux bash command to print the status of nvidia gpu (memory and processes)
!nvidia-smi

Sat Feb  8 04:00:58 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             11W /   70W |       2MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

####Defining the device object (cpu/gpu)

In [ ]:
device = torch.device("cuda")
x = torch.rand(3,3)
print(x)
x.type()

tensor([[0.3964, 0.7500, 0.6854],
        [0.8963, 0.5351, 0.6966],
        [0.7430, 0.6964, 0.7516]])


'torch.FloatTensor'

In [ ]:
x = x.to(device)
x.type()

'torch.cuda.FloatTensor'


###Transferring the tensor to the respective device (here cpu->gpu)
####Transferring the tensor from gpu->cpu


In [ ]:
# Transferring the tensor from gpu->cpu
device_cpu = torch.device("cpu")
x = x.to(device_cpu)
x.type()

'torch.FloatTensor'

In [ ]:
import torch
from torch.autograd import Variable
N=100
D_in=10
H=100
D_out=1

x = Variable(torch.randn(N, D_in), requires_grad=False)
y = Variable(torch.randn(N, D_out), requires_grad=False)
w1 = Variable(torch.randn(D_in,H), requires_grad=True)
w2 = Variable(torch.randn(H, D_out), requires_grad=True)
b1 = Variable(torch.randn(H), requires_grad=True)
b2 = Variable(torch.randn(D_out), requires_grad=True)
learning_rate = 1e-5

for t in range(5000):
    y_pred = ((x.mm(w1)+b1).clamp(min=0).mm(w2)+b2) #FP
    loss = (y_pred-y).pow(2).sum() #Loss computation
    loss.backward() #BP
    w2.data -= learning_rate*w2.grad #WU
    w1.data -= learning_rate*w1.grad #WU
    b2.data -= learning_rate*b2.grad #WU
    b1.data -= learning_rate*b1.grad #WU
    w1.grad.data.zero_() #Reset gradients
    w2.grad.data.zero_() #Reset gradients
    b1.grad.data.zero_() #Reset gradients
    b2.grad.data.zero_() #Reset gradients
    if t%100==0:
      print(loss)
      print(loss.type())

tensor(33387.5234, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(1262.6506, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(593.7207, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(368.3163, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(258.7665, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(192.3369, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(148.0052, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(117.0064, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(94.3429, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(77.3563, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(64.2621, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(53.8821, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(45.5069, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(38.7133, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(33.0925, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(28.4550, grad_fn=<SumBackward0>)
torch.FloatTensor
tensor(24.5454, grad_fn=<SumBackward0>)
torch.FloatTensor
ten